### ISSUE TITLE
Index out of bounds on sprite rendering happens with certain roms

### ISSUE THREAD

**Issue by stianeklund** [stianeklund/chip8#3]
Also occurs with rom: Pong 1P

Note: The issue is likely not with the sprite rendering itself but perhaps with the values the sprites are given, i.e where they're drawn?

Example from Puzzle:

```
thread 'main' panicked at 'index out of bounds: the len is 32 but the index is 32', ../src/libcore/slice.rs:524
stack backtrace:
   1:     0x5631592c1a3f - std::sys::backtrace::tracing::imp::write::h6f1d53a70916b90d
   2:     0x5631592c49dd - std::panicking::default_hook::{{closure}}::h137e876f7d3b5850
   3:     0x5631592c3d8a - std::panicking::default_hook::h0ac3811ec7cee78c
   4:     0x5631592c42d8 - std::panicking::rust_panic_with_hook::hc303199e04562edf
   5:     0x5631592c4172 - std::panicking::begin_panic::h6ed03353807cf54d
   6:     0x5631592c40b0 - std::panicking::begin_panic_fmt::hc321cece241bb2f5
   7:     0x5631592c4031 - rust_begin_unwind
   8:     0x5631592f960f - core::panicking::panic_fmt::h27224b181f9f037f
   9:     0x5631592f95b3 - core::panicking::panic_bounds_check::h19e9bbc59320a57e
  10:     0x56315928e0fe - core::slice::<impl core::ops::Index<usize> for [T]>::index::ha68936569529ff22
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libcore/slice.rs:524
  11:     0x5631592952ac - chip8::cpu::Cpu::step::h916b68e03ef5a11c
                        at /home/stian/dev/projects/chip8/src/cpu.rs:346
  12:     0x5631592983b1 - chip8::main::h8cb217ff3261b5cf
                        at /home/stian/dev/projects/chip8/src/main.rs:54
  13:     0x5631592cc4a6 - __rust_maybe_catch_panic
  14:     0x5631592c3601 - std::rt::lang_start::h538f8960e7644c80
  15:     0x5631592985b3 - main
  16:     0x7f8f78a993f0 - __libc_start_main
  17:     0x563159289dc9 - _start
  18:                0x0 - <unknown>

```

```
  0xD000 => {
                let sprite_x = self.v[x] as usize;
                let sprite_y = self.v[y] as usize;
                let sprite_h = self.opcode & 0x000F;
                self.v[0xF] = 0;

                if DEBUG {
                    println!("X {}, Y:{},H:{}", sprite_x, sprite_y, sprite_h);
                }

                let mut collision = false;

                for j in 0..sprite_h {
                    let row = self.memory[(self.i + j as u16) as usize];

                    for i in 0..8 {
                        if row & (0x80 >> i) != 0 {
                            if self.pixels[(sprite_y + j as usize) % 64][(sprite_x + i as usize) % 64] {
                                collision = true;
                                self.v[0xF] = collision as u8;
                            }
                            self.pixels[(sprite_y + j as usize) % 32][(sprite_x + i as usize) % 64] ^= true;
                        }
                    }
                }
                display.draw_flag = true;
                self.pc += 2;
            }

```

**Comment by stianeklund** [comment]
The reason this happens with Pong1P is that the paddle ends up outside of the screen. It should do this and in Pong (and other Pong roms) you should be able to move the paddle off the screen to the other side. To do this we need to wrap so the value wraps around and doesn't exceed the size of the array.

Why this specifically happens with Puzzle (mentioned above) I don't know, but the reason for it happening with Pong is understandable.

https://doc.rust-lang.org/std/num/struct.Wrapping.html
